server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions_db
    username: postgres
    password: vasanth
springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: fraud-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false