server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: vasanth

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true