server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: postgres
    password: vasanth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.smartbanking.common.dto.TransactionEvent
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false